services:

  backend:

    image: amarbhise/intbuddy-backend:latest

    container_name: intbuddy-backend

    restart: unless-stopped


    env_file:
      - /opt/intbuddy/env/backend.env


    ports:
      - "9090:9090"


    depends_on:
      - mysql
      - redis


    networks:
      - intbuddy-network



networks:

  intbuddy-network:

    external: true
