services:

  backend:

    image: amarbhise97/intbuddy-backend:latest

    container_name: intbuddy-backend

    restart: unless-stopped


    env_file:
      - /opt/intbuddy/env/backend.env


    expose:
      - "9090"


    networks:
      - intbuddy-network



networks:

  intbuddy-network:

    external: true
